import streamlit as st
import json
import os

# Streamlit App Configuration
st.set_page_config(page_title="Expiry Radar", layout="wide")

st.title("Expiry Radar Dashboard (IBM Qiskit Focus)")
st.write("Visualizing upcoming expirations and hidden code issues.")

# Load findings generated by the Bob agent
findings_path = "findings.json"

if os.path.exists(findings_path):
    with open(findings_path, "r") as f:
        findings = json.load(f)
    
    st.subheader(f"Found {len(findings)} expiring items")
    
    # Display each finding clearly
    for item in findings:
        with st.expander(f"{item.get('severity', 'UNKNOWN').upper()} - {item.get('title', 'Unknown Item')} (Breaks on: {item.get('breaks_on', 'N/A')})"):
            st.json(item)
else:
    st.info("No findings yet. Run the Expiry Radar collectors and Bob agents to generate data.")
